version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: donation-platform
        container_name: donation-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    mysql:
        image: mysql:5.7.33
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            # MYSQL_PASSWORD: 123456
            # MYSQL_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - app-network

    nginx:
        image: nginx:1.19.8-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8100:80
        volumes:
            - ./:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks:
            - app-network
